Карточка поста
MikhaiLS9/test_nestjs pull request #1
Opened 2024-04-01 16:40 UTC by MikhaiLS9

2024-04-01 17:46 UTC, harmonyhusher requested changes
Привет. 

Как бы мы не признавали, что фронтенд - не совсем вёрстка, но верстать базовые вещи уметь надо. 
Вёрстка во многих местах не соответствует нужному результату. Текст, отступы и выравнивания неверные. 

_Ошибки и варианты их исправления:_

1. Не используй в CSS строгие указание пиксели. Это плохо в разработке. Так теряется адаптивность/респонсивность вёрстки. 
Единственное место, где ты можешь это использовать - это в page.module.css, где ты четко задаешь границы/отступы и остальные глобальные стили текущей страницы.
Попробуй их задать, и уже затем переделай верстку компонента  <MainCompressed />

```
[app/MainCompressed/MainCompressed.module.css]
  max-width: 1126px;
  width: 100%;
```
Так делать неправильно. Тут должно быть просто width: 100%, а отступы и максимальную ширину должны задаваться в стилях страницы, то есть page.module.css
Убери max-width и задай justify-content: space-between;
Либо убери max-width и задай нужный gap;

2. Хедер и главный страницы НЕ имеют одинаковую ширину. Тоже исправить это. Скорее всего исправится когда избавишься от жестко заданной ширины.

3. Сама карточка. Карточку тоже стоит переделать.

- Избавиться от всех  жестко заданных ширины стилей в файле ItemCompressed.module.css 
- Избавиться от четко заданной высоты. Высота должна складываться из padding, и auto высоты самого контента. Тем более у тебя уже задан box-sizing: border-box в стилях ItemCompressed.module.css 
- Избавиться от четко заданной ширины картинки в карточке. Это не верно. <Image/> компонент Next.js требует заданной ширины и высоты. Прочитай в документации как с этим работать и попробуй переделать это с применением пропсов fill и sizes и заданием стиля
- Расстояние от картинки до контента с текстом создается с помощью margin-top. В идеале стоит это сделать через flex-direction: column и gap. Но это не критично
- Переделай контент с текстом. Сейчас он вообще не понятно как сделан. Избавься от лишней верстки. Пример как должно быть:

```
 <div className={styles.container}>
      <div>
        <h1>Контент</h1> <p>Контент 2</p>
      </div>
      <p>Контент 3</p>
      <div>
        <h1>Контент 4</h1> <button>Контент 5</button>
      </div>
    </div>
```
И соответственно padding должен быть общий и только у container

4. **Главная цель** домашнего задания была выполнена не везде правильно. Ты сделал отлично, что разделил header и компонент страницы, но так делать не стоит. header можно вполне вынести в лейаут страницы, а вот компонент страницы уже оставить в самой странице.
Компонент ItemCompressed ты от слова совсем не разделил на маленькие компоненты. Сделай это и опиши нужные пропсы для: Кол-во лайков, Дата карточки,  Время чтения карточки (слева снизу карточки), и кнопка читать. Все эти 4 блока в ИДЕАЛЕ должны быть отдельными компонентами. Так код станет более читабельный

_На что стоит обратить внимание:_ 

1. В Headline компоненте ты можешь не создавать целый интерфейс ради одного children. В React существует уже встроенный тип React.PropsWithChildren, и в итоге пропсы Headline будут { children }: React.PropsWithChildren
2. Создай отдельную папку для реиспользуемого контента) Эта правильный тон кода. Создай папочку и файл к примеру consts.ts и перенеси туда свой объект ITEMS_DATA. И не забывай о нейминге) Достаточно просто красивого и лаконичного камел кейса - items или itemsData
3. Попробуй подключить шрифты) Необязательно, но для себя можешь попробовать
([](https://www.youtube.com/watch?v=L8_98i_bMMA&ab_channel=LeeRobinson))

2024-04-01 17:47 UTC, harmonyhusher commented
https://www.youtube.com/watch?v=L8_98i_bMMA&ab_channel=LeeRobinson  
полезное видео по шрифтам https://www.youtube.com/watch?v=L8_98i_bMMA&ab_channel=LeeRobinson

2024-04-02 18:25 UTC, MikhaiLS9 reviewed
убрал высоту и ширину

2024-04-02 20:06 UTC, harmonyhusher commented
Привет. 

Теперь всё круто)

2024-04-02 20:45 UTC, merged